CREATE TABLE Clients
(
ClientId INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Phone CHAR(12) NOT NULL
)

CREATE TABLE Mechanics
(
MechanicId INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Address NVARCHAR(50) NOT NULL
)

CREATE TABLE Jobs
(
JobId INT PRIMARY KEY IDENTITY,
ModelId INT NOT NULL,
Status NVARCHAR(11) DEFAULT 'Pending' CHECK (Status IN ('Pending', 'In Progress', 'Finished')) NOT NULL,
ClientId INT FOREIGN KEY REFERENCES Clients(ClientId) NOT NULL,
MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
IssueDate DATE NOT NULL,
FinishDate DATE
)

CREATE TABLE Models
(
ModelId INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) UNIQUE NOT NULL
)

ALTER TABLE Jobs
ADD FOREIGN KEY (ModelId) REFERENCES Models(ModelId)

CREATE TABLE Orders
(
OrderId INT PRIMARY KEY IDENTITY,
JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
IssueDate DATE,
Delivered BIT DEFAULT 0
)

CREATE TABLE Vendors
(
VendorId INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Parts
(
PartId INT PRIMARY KEY IDENTITY,
SerialNumber NVARCHAR(50) UNIQUE NOT NULL,
Description NVARCHAR(255),
Price Decimal(15,2) CHECK (Price > 0 AND Price <= 9999.99) NOT NULL,
VendorId INT FOREIGN KEY REFERENCES Vendors(VendorId) NOT NULL,
StockQty INT DEFAULT 0 CHECK (StockQty >= 0) NOT NULL
)

CREATE TABLE OrderParts
(
OrderId INT REFERENCES Orders(OrderId) NOT NULL,
PartId INT REFERENCES Parts(PartId) NOT NULL,
Quantity INT DEFAULT 1 CHECK (Quantity > 0) NOT NULL,
CONSTRAINT PK_OrderId_PartId PRIMARY KEY (OrderId, PartId)
)

CREATE TABLE PartsNeeded
(
JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
PartId INT FOREIGN KEY REFERENCES Parts(PartId) NOT NULL,
Quantity INT DEFAULT 1 CHECK (Quantity > 0) NOT NULL
CONSTRAINT PK_JobId_PartId PRIMARY KEY(JobId, PartId)

)