CREATE DATABASE University
USE University
CREATE TABLE Subjects
(
	SubjectID INT PRIMARY KEY IDENTITY,
	SubjectName VARCHAR(50) NOT NULL
)
CREATE TABLE Agenda
(
	StudentID INT UNIQUE,
	SubjectID INT UNIQUE FOREIGN KEY REFERENCES Subjects(SubjectID),
	CONSTRAINT PK_Student_Subject_ID PRIMARY KEY (StudentID, SubjectID)
	
)
CREATE TABLE Students
(
	StudentID INT IDENTITY PRIMARY KEY,
	StudentNumber INT UNIQUE NOT NULL,
	StudentName VARCHAR(50) NOT NULL,
	MajorID INT NOT NULL
)
ALTER TABLE Agenda
ADD CONSTRAINT FK_StudentID FOREIGN KEY (StudentID) REFERENCES Students(StudentID) 
CREATE TABLE Majors
(
	MajorID INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL
)
ALTER TABLE Students
ADD CONSTRAINT FK_MajorID FOREIGN KEY (MajorID) REFERENCES Majors(MajorID)
CREATE TABLE Payments
(
	PaymentID INT PRIMARY KEY IDENTITY,
	PaymentDate DATE NOT NULL,
	PaymentAmount DECIMAL(10,2) NOT NULL,
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)